name: Publish Package to npmjs
on:
  push:
    tags:        
      - '*'
    branches:
      - main
jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/') && github.ref_name == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.10'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9
      - name: Install dependencies
        run: pnpm install
      - name: build
        run: pnpm run build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
